### ISSUE TITLE
Implement Image Upload Feature

### ISSUE THREAD

**Issue by rottem1357** [rottem1357/android#12]
### Description:
- Use ImagePicker to allow users to upload an image when adding a new recipe.
- Store the image URI in the Room database and display it as part of the recipe details.

### Tasks:
- [ ] Integrate ImagePicker for image selection.
- [ ] Store image URI in Room database.
- [ ] Display image in `RecipeDetailFragment`.

### Reference:
Follow [step 9](#) of the project plan.
