### ISSUE TITLE
Search Recipes by Ingredients

### ISSUE THREAD

**Issue by rottem1357** [rottem1357/android#13]
### Description:
- Allow users to input a list of ingredients they have.
- Search the local Room database for recipes that match the available ingredients.

### Tasks:
- [ ] Create search form for inputting ingredients.
- [ ] Implement logic to query Room database based on ingredients.
- [ ] Display matching recipes in `RecipeListFragment`.

### Reference:
Follow [step 10](#) of the project plan.
